### ISSUE TITLE
More care, and control, over what WebRTC reality we get

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/webxr-api#12]
https://github.com/mozilla/webxr-api/blob/a81c0ec41ecf60c583fbb06d65a03b0f2dac3bb6/examples/polyfill/reality/CameraReality.js#L44-L46

If we look at JSARToolkit, AR.js and argon.js's WebRTC reality, all attempt to constrain the selection of the reality.  Mostly, they try to find a relatively low res (~320x240) if available.  One question, of course, is if we need that:  is it the case that we can render the video to any sized canvas we want, so we can display at high res and (if we want to do tracking) get the pixels at lower res?

This might (also) be an example of where we'd want to have a "platform specific extenstion API" to manager WebRTC video.  In addition to choosing cameras or resolutions, this  might also let us (for example) connect to a remote video stream and do AR on it, or run off a remote file.   Neither of the later of these is urgent, but selecting cameras might be.  And, more importantly, if continues to force us to deal with "platform specifics".

**Comment by joshmarinacci** [comment]
It's my understanding that projecting the full size camera view into a video div is essentially free. It's all done in hardware with textures, even if you put other content on top of it (using render layers inside webkit). Scaling it down to get a lower res version to hand to JS costs more because we have to read the texture back and then scale it. That said, having access to a second lower res version will open up new features, so we shouldn't limit it. For now, though, I'm happy just blitting the camera view into the background.

- Josh

**Comment by blairmacintyre** [comment]
So, the goal here would be to start exposing our view on how to do "high performance vision" using the web.  So, some thoughts:
- the end goal is "programmers can write/load javascript and/or webassembly code to process sensor data efficiently each frame".  I think we want the possibility of leveraging multiple cores, etc., so we probably want these in in something like a Worker, or perhaps a "SensorWorker" that gets triggered each time there is data.  Yes?   The simple approach is just a callback (synchronous) but that limits ability to parallelize;  however, parallelization only matters if we can efficiently share data (we can, right?)
- for a Reality, we need to have a way to expose the set of sensors available to it to set these up
- for a camera sensor, we want to "try to set" and/or query the resolution, get the camera intrinsics (in this case, we make them up based on what we're telling the app the FOV is; for new platforms, you can get the intrinsics from ARKit, ARCore, etc).  In this case, we want to constrain the max size, so we might want to say what the max width or height is (256? 320?).
- each frame, we need to get the data, and probably thus need to have a way to say "synch with sensor workers" at the point we need it.

We can demonstrate this by restructuring the JSARToolkit to work in this manner (aside:  we should eventually try to build that using WebAssembly).

**Comment by joshmarinacci** [comment]
I believe there is something called a SharedArrayBuffer to enable efficient data sharing between the main thread and worker threads. Of course, I bet you could do a lot of this processing better on the GPU, at least if we are talking about vision algorithms.

https://webkit.org/blog/7846/concurrent-javascript-it-can-work/

**Comment by joshmarinacci** [comment]
Once our stuff is out, do you think we could get the AR.js guy  (Jerome?) to do the refactoring work to build on top of our stuff?  It would let him still control his own API and do all the fun marker things, but build on top of something more portable and powerful.

-j

**Comment by blairmacintyre** [comment]
@joshmarinacci yes, that's what I was remembering, SharedArrayBuffer's.  

The larger question is the architecture.  For example, should we ask people to prepare a worker, and give it to us, or prepare a script that has a certain API that _could_ be used in a worker, that we'll either fire off in a worker, or call synchronously, depending on the platform and so forth (e.g., we might or might not want to fire off too many threads, and in a native implementation, we might actually have reasons to choose this).

We could have them pass in an object with a certain API, and we could wrap it in a worker or just call it.

As for WebAssembly/Javascript vs GPU:  I agree 100%.  We actually need to provide _both_, for two reasons: 
- people might have code that only works in one of two places
- the platform may only provide image/sensor data in one or both places (e.g., perhaps the image data isn't in memory, only the GPU)?

I am unclear as to what the best API would be to set up something to process video frames that are already in texture memory.  I suspect they would need to prepare a shader, for example?  But, we may not want to deal with that until we get someone involved who has experience doing CV with GPU shaders in (probably) WebGL2.

**Comment by blairmacintyre** [comment]
As for how to demo it;  I've already done a bit of hacking on the JSARToolkit code and could pretty easily modify it to support a "here's a frame, and camera info, process the data".
