### ISSUE TITLE
system state should be exposed as events

### ISSUE THREAD

**Issue by joshmarinacci** [mozilla/webxr-api#20]
I'd like to put a dialog on top of the screen which says to move around until the system is fully initalized and found the floor anchor. Currently there is no API to get this. I can sort of do it by querying for the floor anchor and seeing what I get back, but this doesn't feel reliable becuase I can't tell if the anchor is valid.  We should expose the state of the system through a series of events, similar to how XMLHttpRequest gives you detailed events for different parts of a request.

**Comment by blairmacintyre** [comment]
Ideas on a cross platform way?  For example, is if fair to assume that any given platform has a "tracking system" and it could be in some sort of state?  So, not ARKit specific?  

It seems like Hololens, ARKit, ARCore and Tango should all deal with this.   I wonder what the common baseline behavior is.
