### ISSUE TITLE
Declarative?

### ISSUE THREAD

**Issue by trusktr** [mozilla/webxr-api#21]
Do the ideas here include a declarative (HTML) language for 3D?

**Comment by blairmacintyre** [comment]
The API is lower level than that;  this is more akin to WebVR (which this should supersede, actually) or other low-level APIs.  

That said, we'll be integrating this with AFrame (aframe.io), an initial version is being worked on in https://github.com/arturitu/aframe-xr

And there's no reason other declarative specs (e.g., X3DOM, ReactVR, etc) won't also shift to supporting the full range of MR.
