### ISSUE TITLE
How should we support platform specific APIs?

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/webxr-api#9]
We've talked about it, here and there.  Over time we will expose more and more "generic" APIs that we think can be supported in many places (e.g., perhaps plane detection).  

But, to explicitly control the platform, there will be some custom APIs needed
- ADF control on Tango (and probably ARCore), similar but different ideas on WindowsMR, probably something similar when ARKit matures.
- loading image targets or models on platforms with those kinds of trackers.  
- etc

Should we assume `webxr.platform.name` as a set of namespaces and go from there?

**Comment by VestigeJ** [comment]
I’m a bit of an outsider but I’m watching development for XR on the web in several places. Could the team leverage Kronos’ work for platform specific API’s? 
https://www.khronos.org/openxr

**Comment by blairmacintyre** [comment]
I think the OpenXR stuff is at a very different level right now -- I agree that it will be extremely useful as a way to implement some of this, if they ever take on the AR tech/capabilities, but they are currently pretty focused on VR.  

They will need to do some cross-platform work on AR tech at some point, and if they tackle any of these things in a cross-platform way, we (and others) could leverage that.

BUT, it's unclear when or if any of this will truly be able to be hidden.  For example, neither Microsoft nor Google has indicated they have any interest in make the ADFs (Tango) and Hololens tracking dataset open or compatible.  As long as they are black boxes, and work differently, hiding them will be hard.
